### PR TITLE
[dnd 3.5] Complete Champion, Church, implement The Ruby Temple #483

### PR DESCRIPTION
**Pull request by marcalff**
Implemented ability categories for all churches.
Implemented The Ruby Temple church.

See file complete_champion/README-church.txt

### CODE REVIEW

**Comment by marcalff** [comment]
Please find here a contribution to implement churches from the Complete Champion.
Only The Ruby Temple is fully implemented for now.
Comments welcome, before I rinse and repeat for other churches.

**Comment by BahamutDragon** [comment]
Mate,

I think you are misusing the parent categories and making it a bit too complicated.
Is the intent for this to show up anywhere on the character sheet?

Does the current implementation actually work as desired.

**Comment by marcalff** [comment]
Thanks for looking at it.

Categories are dedicated to a church, and only displayed in the pcgen UI.
Only the categories relevant for the character church are displayed,
categories for other churches are not visible,
to avoid cluttering the UI.
This is why there are so many categories defined, yes.

Now, for a given church, there are 2 categories:
- one is for the "affiliation criteria", used to record all the actions a
  character did, that grants a bonus point for the church
- one is for the "rank" attained.

This organization actually mirrors the book presentation.

Once a character has a rank, the special ability given as a bonus by this
rank is visible in the output sheet.

For example for a character with deity Wee Jas (only the Ruby temple is
fully implemented in this patch, as documented in the pull request)

- Create a character, with deity Wee Jas
- See in the Church tab, that the character is eligible to membership for
  the ruby temple
- Take the ruby temple membership
- The following additional categories are displayed then: Rube Temple
  Affiliation Criteria, and Ruby Temple Rank.
- See that some abilities are automatically granted, typically the ones that
  depends in level, skill, etc, in the affiliation criteria category.
- The player can take manually extra abilities, to document for example
  that the character defeated a Monster of CR x, converted a member to the church,
  etc, all per the rules for this church.
- The resulting score is computed and visible in the Ruby Temple Rank category
- Once the score is enough to claim a rank, it can be taken
- Taking a rank (for example Ruby Temple Crystal Novice) gives the related
  bonus (Ruby Temple Crystal Novice Bonus), which is the benefit in terms of
  game play.
- Only the bonus granted (for example Ruby Temple Crystal Novice Bonus) is displayed in
  the output sheet (it is a special ability), everything else is UI only.

Everything posted was tested, and works as intended.

This is as far I could go with it,
any concrete idea to simplify this is of course welcome.

Regards,
-- Marc

**Comment by marcalff** [comment]
I forgot to mention,
The Ruby Temple is currently used in a gaming session.
I am now working on The Shining Light Of Pelor, for another player in our group.

**Comment by BahamutDragon** [comment]
I see. Proper method is one, maybe two parent categories. The use sub categories and utilize type to filer the correct abilities. Following KEY naming convention prevents overlap. I can do up a mock Sunday. Have other things to handle before then.

**Comment by marcalff** [comment]
This would be awesome,
Thanks.

**Comment by BahamutDragon** [comment]
Mate, comment to let me know when this is ready.

**Comment by marcalff** [comment]
BahamutDragon,

I just pushed the fixes, testing looks ok.
Thanks for the suggestions and the mockup, it helped to figure out how to organize this.

Regards.

**Pull request merged**
