### PR TITLE
BE feat choice

### PR DESCRIPTION
**Pull request by rmvhoek2**
Additional fixes to bonus feats in BE, including Anointed Knight, Exalted Arcanist, Sword of Righteousness, Vassal of Bahamut, and Wonderworker

### CODE REVIEW

**Comment by BahamutDragon** [comment]
Hi Mate, 

You have branched from the master branch and are now trying to apply it to the 6.04.01 branch. This will not work. This PR will result in multiple errors for anyone using pcgen 6.04.01.

6.04.01 can be merged into master, but master cannot be merged into 6.04.01. There are incompatible changes in master that only work with an autobuild of pcgen. 

I will isolate the changes you appear to be trying to push in, and incorporate those into the build. 

Best,

**Comment by rmvhoek2** [comment]
Sorry - still trying to get my head around Git. I apologize for causing you extra work. I can redo the pull request against master if that is easier for you.

A question if you have time:
Looking at the treatment of bonus feats in the files, it appears that some instances follow the model of creating a "bonus_feat_count" variable that gets computed or incremented in the classes file, while others just define the number of entries for the pool in the abilities file (as per your earlier comment). Are there cases when the former approach is preferred? I originally used the "count" method because that seemed to be how bonus fighter feats were implemented in the core files. Any guidelines for when this is appropriate or inappropriate?

Thanks

**Comment by BahamutDragon** [comment]
Mate, I have pushed in the BE feat changes you wanted to both the master and 6.04.01. 

Answer to your question: "Count" was the preferred method for the jep variable system, that is until the replacement formula parser became the hot topic. That is a massive changer to the syntax. With ability pools being prefixed with "Pool.x" instead of appended count, I am switching to "DEFINE:POOL_x" to make the transition for that easier.  "POOL_x" will be easier to change to "Pool.x". While a term like "DEFINE:FighterFeatCount" has no easy change. Best to keep up with the official pcgen changes. Less work to do when the change happens. 

If you look at the 5e set, you will see that all calculations are handled directly in the ability. Only variable in the class, is the CL > ClassNameLVL method. 

BONUS:VAR is eventually going away. The terms we use with that will transition to something else.
Count, Bonus, etc., all were for the single var system. The proposed changes would switch from BONUS:VAR|FighterFeatCount|FighterLVL/2 to  MODIFY:VAR=POOL.Fighter_Feat|SOLVE|value()+classlevel(Fighter)/2 or something similar.

Many of the bonuses had a type. I am given to understand that those will be part of the naming itself.
Object.Modifier
Pool.Fighter_Feat
ToHit.Enhancement
ToHit.Morale
ToHit.Sacred
AC.Sacred
AC.Deflection

Those values will be held in a central file location. This is why 5e is built to be more central file focused, and putting to practice the concepts the formula parser will implement. Here is an example of AC. A natural armor bonus is currently BONUS:COMBAT|AC|x|TYPE=NaturalArmor. Instead becomes	BONUS:VAR|AC_NaturalArmor|0|TYPE=Base in each race or item that grants. And then there is only one "BONUS:COMBAT|AC|AC_NaturalArmor|TYPE=NaturalArmor" held in a central file. This is my attempt to coordinate the new incoming ideas and make them easier to switch to.

Use whichever method you are comfortable with. The formula parser will only affect the master branch.

To help get your head wrapped around git, you will need to Pull updates directly from this repo. Be sure to pull updates for both branches. Then create new branches directly from 6.04.01 to ensure the only updates in the commit are compatible with 6.04.01. 

There is a reasoning behind the madness. 6.04.01 is intended to contain patches that support pcgen version 6.04.01. While master will only be compatible with the latest versions of pcgen. 

Best,

**Comment by rmvhoek2** [comment]
Wow - thanks for taking the time to give a very complete answer! It's always easier for me if I know the "why" as well as the "what", and you've supplied that. I'll bear all this in mind for my next bit of work.

**Pull request closed without merging**
