### PR TITLE
6.08

### PR DESCRIPTION
**Pull request by Jasoneagle**
Last Pull Request files where not in Correct Folders Re-uploaded and Re submitted for Pull.
I Began work on Races of Ansalon Book for Dragonlance Setting.
Added Rest of Dragonlance Coin gave them all SORTKEY and KEY tags to Keep them Separate from any other Source Coin.
Updated Book Abbreviation List to Include Races of Ansalon  (RoA).
Additional file Notes.txt Included as a Request for Thoughts on Modding The Hoopak to allow Custom Versions.

### CODE REVIEW

**Comment by BahamutDragon** [comment]
Mate, 

Are you trying to merge the 6.08 branch back into the master branch?

**Comment by Jasoneagle** [comment]
Just the 6.08 branch.

**Comment by BahamutDragon** [comment]
Then you did the PR incorrectly. You are attempting to merge the 6.08 into the master branch.

image

**Comment by Jasoneagle** [comment]
Wow must have been really tired when I did it. I'll resubmit

**Pull request closed without merging**
