### PR TITLE
cleaned up Cloistered cleric (had broken Aura level by using ClericLVL).

### PR DESCRIPTION
**Pull request by FerretDave**
Cleaned up Acolyte of the Skin to add Wear Skin detail.

### CODE REVIEW

**Comment by BahamutDragon** [comment]
Mate, I am beginning to suspect many of your fixes are directed at pre-existing characters with persistence problems. Some of these may be better off as a pcgen team request instead of constant data hacks. A simple new character exhibits no sign of the issues these fixes are claiming to correct and is causing new problems. 

For example, AUTO:LANG being moved to the race. This is an incorrect move. Forgotten Realms version and Standard version grant different languages. Moving that to the race nullifies that distinction, and removes the subrace's ability to handle that correctly.

BONUS:VAR|DarkvisionRange|-DarkvisionRange is a zero sum result, or more precisely, an infinite loop. You have a Var of 60, the logic you gave says -60. Var is now 0, logic changes to -0, result is back to 60. This repeats indefinitely. Result, no change.

The martial weapon and darkvision are removed for the Aasimar. Which was the focus on your last request, support Lesser Aasimar. A new character works, the old may not since we have changed how things are supposed to work. Again, a potential persistence issue that would be better addressed by the pcgen team. RACETYPE on the race being moved to an ability may not easily update. Try altering the base race to None, save, close, reopen, switch back the race to Aasimar.

The other Planetouched races, like the Tiefling and the Genasi, likely need the BONUS:VAR|DarkvisionRange removed. I honor the requests made first. The rest happens when time permits.

It is easier to submit PRs from master, however, common practice is to separate out each feature in its own isolated branch. With all of your issues crammed into one mega PR, it does tend to make things a bit difficult. Any problem holds up the entire PR, as is the case now.

**Comment by FerretDave** [comment]
Greetings,

Persistence... It's been a while and I thought all of those types of issues
had been coded out now, I'll have to back these changes up a bit and retest
- yes, I was using an existing character for it all, and didnt' think to
test persistence...

Problems with branching is that I'm rarely just fixing one thing - as I'll
fix bits, restart pcgen, reload sources, reload character(s) and then
retest output, I tend to work on multiple fixes at once.

Once I've gotten most things working for my current game - migrating
existing paper characters to PCGen, then I'll be able to start sorting them
separately and branching for each different fix as I add it.

The LANG and VISION hacks can be dropped from the PR, but the rest of it
should all be good.

Cheers
D

**Comment by FerretDave** [comment]
Greetings,
Ok, removed those LANG and VISION 'fixes', so the latest PR should be acceptable.

However, just created a new character, aasimar, forgotten realms variant, and adding the lesser planetouched did not remove the darkvision.
Also, adding the forgotten realms subtype should give add Celestial as a bonus lang.

Can you add the appropriate to resolve those please? Definately not a persistance error..

Cheers
Dave

**Comment by FerretDave** [comment]
Greetings,
Ok, removed those LANG and VISION 'fixes', so the latest PR should be
acceptable.

However, just created a new character, aasimar, forgotten realms variant,
and adding the lesser planetouched did not remove the darkvision.
Also, adding the forgotten realms subtype should give add Celestial as a
bonus lang.

Can you add the appropriate to resolve those please? Definately not a
persistance error..

Cheers
Dave

**Comment by BahamutDragon** [comment]
Forgotten Realm Aasimars lose Celestial as an automatic, instead gaining a region specific language instead. There is nothing to alter for the bonus languages, they gain all spoken languages to choose from.

**Comment by FerretDave** [comment]
Greetings,
My apologies, we all thought they kept Celestial... our mistake.

Thanks again for all your work on this, your sources are great, and are
very much appreciated.

Cheers
Dave

**Pull request merged**
