### PR TITLE
Changes to allow a cohort and followers with the Leadership feat

### PR DESCRIPTION
**Pull request by jagbear**
Changes to allow a cohort and followers with the Leadership feat

### CODE REVIEW

**Comment by BahamutDragon** [comment]
Mate,

Conflicted first off. Secondly, is my patch not sufficient for you?

**Comment by BahamutDragon** [comment]
https://github.com/BahamutDragon/pcgen/commit/f3d2bd21f636fd77121e15ac99b0e273af9adc0e
or 
https://github.com/BahamutDragon/pcgen/commit/7d6ca19034157f403775169ce78585e1cb18c33b

**Comment by jagbear** [comment]
Didn't see it until after I had already put in the pull request.  I will
test your changes and remove the pull request.

On Sun, Apr 10, 2016 at 2:09 PM, Bahamut <notifications@github.com> wrote:

> Mate,
>
> Conflicted first off. Secondly, is my patch not sufficient for you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BahamutDragon/pcgen/pull/467#issuecomment-208045990>
>



-- 

   JD


  ("`-''-/").___..--''"`-._
   `6_ 6  )   `-.  (     ).`-.__.`)
   (_Y_.)'  ._   )  `._ `. ``-..-'
 _..`--'_..-_/  /--'_.' ,'
(il),-''  (li),'  ((!.-'

**Comment by BahamutDragon** [comment]
Mate,

I hope you find the patch satisfactory. Cohort and Followers are separated. Followers are granted if the user adds the "Grant Followers" optional ability under the Leadership group, which happens to include all of the Leadership Modifiers. The follower option is set up to separate them out by their designated levels. I also coded this up to only display the Followers and Cohort that have 1 or more available selection. I tested it several times to get the desired results.

Best,

**Pull request closed without merging**
