### PR TITLE
fixed LA for Half-Ogre and Centaur

### PR DESCRIPTION
**Pull request by myrlyn**
using the BONUS:VAR|LevelAdjustment|2|TYPE=Base syntax does not work in PCGen, added LEVELADJUSTMENT tag.

### CODE REVIEW

**Comment by BahamutDragon** [comment]
When something is not working, it is best to find out why and address the root cause, not patch over it.

**Comment by myrlyn** [comment]
I understand that as a general principle- but the BONUS:VAR|LevelAdjustment|X setup overall doesn't work, it's not just that it's not working in this case.  
PCGen has builtin level adjustment tracking - The LEVELADJUSTMENT tag. Is there a reason for tracking level adjustment in a variable rather than using the pre-existing LEVELADJUSTMENT tag?  It seems that the current system in the dataset is designed to track a LevelAdjustment variable, so that the universal_rules lst files can assign you a custom-coded ability that assigns you a template which has the appropriate LEVELADJUSTMENT tag.  This seems not only far more complicated than simply using the LEVELADJUSTMENT tag directly in Races and Templates, it means that the Level Adjustments of Races and Templates don't display in the UI.  Am I missing something?

**Comment by BahamutDragon** [comment]
I will summarize:
"Lesser Planetouched" template implementation request led to the discovery that LevelAdjustment was not functioning with accuracy when a negation component was added. Having two different systems to handle the same issue was not optimal, which prompted the system-wide adoption of a working method.

The var system does not show changes on the UI. A compromise I am willing to tolerate for a system that actually works as intended.

**Comment by BahamutDragon** [comment]
To clarify a point, LevelAdjustment has two factors to consider.

1) It alters the Experience Required value to the increased or decreased level chart value (Seen on the character sheet)
2) It displays the alteration of level in the GUI. (Only seen on the Race Tab and Template Tab)


My intention is always to have (1) work. (2) does no good if the final results are incorrect. I hope that clarifies my reasoning sufficiently for you mate.

By allowing your patch, (1) breaks for these two races (incorrect required experience is displayed), and (2) is the only correct value. In order for your patch to work, you have to remove the BONUS portion, but then anything later built to make use of the var system will have no affect on these two races. That is the toss up for me, correct UI or correct XP. I prefer to have a consistent system. It causes less confusion for those that desire to contribute. 

This may all be a fruitless discussion. The bonus system is being deprecated for the next pcgen development cycle, and likely a good number of tags that reflect numbers, such as levelAdjustment, will be incorporated into the replacement formula system.

A compromise if you will. If you can effectively address the Aasimar + Lesser Planetouched issue (The root cause of the whole abandoning of straight LEVELADJUSTMENT on races and templates), I will implement your solution system-wide.

Best,

**Comment by FerretDave** [comment]
Greetings,

Was the LEVELADJUSTMENT failure to handle negation logged as a bug?

Cheers
D

**Comment by myrlyn** [comment]
Yeah, that makes perfect sense.  I'll refactor the entries I had written
using the LevelAdjustment tag rather than variable.
I'm also happy to open a bug with the pcgen team regarding the
Aasimar/Lesser Planetouched issue in hopes that it's solution will make it
into the next release even if the LevelAdjustment tag doesn't get
deprecated.

**Comment by myrlyn** [comment]
Looks like this may be fixed in PCGEN
Testing in the latest BETA of PCGEN (6.06.00 RC3)
I tried switching Aasimar from using BONUS:VAR tags to the LEVELADJUSTMENT
tag (for the Standard subrace)
I created a Level 1 Fighter, and set Race to Human - Current XP=0
set Race to Aasimar - Current XP=1000
Applied Lesser Planetouched Template - Current XP=0
Are there other test cases I should evaluate?

Jonathon Lee Walker

**Comment by BahamutDragon** [comment]
Mate,

Why are you testing an older release candidate? PCGen officially released 6.06.00 on March 1st.

@FerretDave  does the change work for you?

Best,

**Comment by FerretDave** [comment]
Greetings,
I'm on 6.06, but am focused on my other campaign currently (3 times a year
game, this weekend, all weekend), so wont be testing the Aasimar till next
week (that campaign plays next tuesday, but won't need a new printout yet).

Note that the PDF OS has a problem with long weapon descriptions wrapping -
that has been fixed so the latest autobuild should be worth grabbing,
however last time I tried it I got lots of other errors so stuck with 6.06
as I needed to focus.

Cheers
D

**Comment by BahamutDragon** [comment]
@myrlyn I think we have given @FerretDave ample time to respond. Make the necessary changes to the entire system. Verify things are working, and then update this PR.

Best,

**Comment by FerretDave** [comment]
Sorry, been busy. Go for it.

**Comment by myrlyn** [comment]
Pushed new Commit which should convert all races and templates to use the LEVELADJUSTMENT tag.

**Comment by myrlyn** [comment]
Updated LEVELADJUSTMENT tags, verified negation works.

**Pull request merged**
