### PR TITLE
fixes to prevent load errors using PCGen 6.08.08

### PR DESCRIPTION
**Pull request by FerretDave**
removed load errors by matching up AGESET values correctly and removing reference to 'HANDED'

### CODE REVIEW

**Comment by BahamutDragon** [comment]
It has conflicts.

**Comment by FerretDave** [comment]
looks like I had the master branch open and tried to commit against 6.08 ?

**Comment by FerretDave** [comment]
Sorry, looks like I'd got 608 and master mixed up on my branches, the fixes
had already been done.

**Comment by FerretDave** [comment]
Greetings,

Sorry, can you advise on this, I thought AGESET was supposed to be
standardised, however we've got different settings throughout.

I'm not sure what should be corrected here, but the loader (6.08.08, using
the 6.8 branch) gives errors:

22:23:41.582 INFO main Main:138 Starting PCGen v6.08.00 RC8
22:23:41.619 INFO main LanguageBundle:134 Initialising language bundle with
locale en_US.
22:23:57.116 INFO Thread-2 SourceFileLoader:534 Loading game Bahamut35e and
sources [Campaign: Petes Tuesday TearingOfTheWeave game].
22:24:00.230 SEVERE Thread-2 BioSet:634 Found second (non-identical) AGESET
in Bio Settings
file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst
for Region: None Index: 0 using the existing 0|Adulthood
22:24:00.230 SEVERE Thread-2 BioSet:634 Found second (non-identical) AGESET
in Bio Settings
file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst
for Region: None Index: 1 using the existing 1|Middle Age
STAT|STR,CON,DEX|-1 STAT|INT,WIS,CHA|1
22:24:00.230 SEVERE Thread-2 BioSet:634 Found second (non-identical) AGESET
in Bio Settings
file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst
for Region: None Index: 2 using the existing 2|Old STAT|STR,CON,DEX|-3
STAT|INT,WIS,CHA|2
22:24:00.231 SEVERE Thread-2 BioSet:634 Found second (non-identical) AGESET
in Bio Settings
file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst
for Region: None Index: 3 using the existing 3|Venerable STAT|STR,CON,DEX|-6
STAT|INT,WIS,CHA|3
22:24:00.231 SEVERE Thread-2 BioSetLoader:97 Incompatible Index for AGESET
in Bio Settings
file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst:
2 and 4 for Old
22:24:00.231 SEVERE Thread-2 BioSetLoader:97 Incompatible Index for AGESET
in Bio Settings
file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst:
3 and 5 for Venerable
22:24:00.232 SEVERE Thread-2 BioSetLoader:97 Incompatible Index for AGESET
in Bio Settings
file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/players_guide_to_faerun/pg_biosettings.lst:
4 and 2 for Old
22:24:00.233 SEVERE Thread-2 BioSetLoader:97 Incompatible Index for AGESET
in Bio Settings
file:/C:/Utils/GitHub/pcgen/data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/players_guide_to_faerun/pg_biosettings.lst:
5 and 3 for Venerable

Looks like the various 'other' files ought to be altered to match the
universal_rules/ur_biosettings?

/GitHub/pcgen/data/35e/wizards_of_the_coast
$ grep -r AGESET: |grep -v PREAGESET
campaign_settings/forgotten_realms/champions_of_ruin/cr_biosettings.lst:AGESET:0|Adulthood
campaign_settings/forgotten_realms/champions_of_ruin/cr_biosettings.lst:AGESET:1|Middle
Age
campaign_settings/forgotten_realms/champions_of_ruin/cr_biosettings.lst:AGESET:2|Old
campaign_settings/forgotten_realms/champions_of_ruin/cr_biosettings.lst:AGESET:3|Venerable
campaign_settings/forgotten_realms/players_guide_to_faerun/pg_biosettings.lst:AGESET:0|Adulthood
campaign_settings/forgotten_realms/players_guide_to_faerun/pg_biosettings.lst:AGESET:1|Middle
Age
campaign_settings/forgotten_realms/players_guide_to_faerun/pg_biosettings.lst:AGESET:2|Old
campaign_settings/forgotten_realms/players_guide_to_faerun/pg_biosettings.lst:AGESET:3|Venerable
campaign_settings/forgotten_realms/races_of_faerun/rac_biosettings.lst:AGESET:0|Adulthood
campaign_settings/forgotten_realms/races_of_faerun/rac_biosettings.lst:AGESET:1|Middle
Age
campaign_settings/forgotten_realms/races_of_faerun/rac_biosettings.lst:AGESET:2|Old
campaign_settings/forgotten_realms/races_of_faerun/rac_biosettings.lst:AGESET:3|Venerable
core/universal_rules/ur_biosettings.lst:AGESET:0|Undefined
core/universal_rules/ur_biosettings.lst:AGESET:1|Youth
core/universal_rules/ur_biosettings.lst:AGESET:2|Adult
core/universal_rules/ur_biosettings.lst:AGESET:3|Middle-Aged
core/universal_rules/ur_biosettings.lst:AGESET:4|Old
core/universal_rules/ur_biosettings.lst:AGESET:5|Venerable
supplement/expanded_psionics_handbook/xph_biosettings.lst:AGESET:0|Adulthood
supplement/expanded_psionics_handbook/xph_biosettings.lst:AGESET:1|Middle
Age
supplement/expanded_psionics_handbook/xph_biosettings.lst:AGESET:2|Old
supplement/expanded_psionics_handbook/xph_biosettings.lst:AGESET:3|Venerable

Happy to make the changes, just not sure which to to change to..

Cheers
Dave

**Pull request closed without merging**
