### PR TITLE
Minor DESC and load fixes to Core & Forgotten Realms

### PR DESCRIPTION
**Pull request by FerretDave**
The Tome of Magic supplement is not loading correctly, I've corrected one typo and some skill references, but there are still other errors - none affecting things I need or know about from the book though, just needs some cleanup, Can you review that source please.

### CODE REVIEW

**Comment by BahamutDragon** [comment]
Mate,

Some of this looks like personal preferences which should be handled in a personal custom source. For Instance, the outputname on an object to reduce characters used, or altering actual feat text from the original source.

Some is just wasting file space, like Armor Don rates. All commented out and does not appear to serve any purpose.

Then we have actual fixes, such as misspelled class names and class skills.

Quite a chunk of stuff to sort through.

As set up, it is an all or nothing proposition. 

My preference is the source book sets should match the actual sources as best as possible. Alter spells to include the real description is fine, but altering text to fit a preference beyond that should be a separate personal source loader. That avoids personal tastes from cluttering up the original files and allows others to choose the originals or customize if they so choose.

If you can handle placing the personal customizations into a separate custom source over in the homebrew folder, that would be fantastic.

The Tome of Magic patches look good. 

Best,

**Comment by FerretDave** [comment]
Greetings,
Yeah, you're right, the desc stuff I should keep as local homebrew - I
prefer to change a variety to make it look cleaner and more relevant on the
output, but as you say, it's personal preference.

I'll move the DESC stuff out.

I still can't get the Lesser Aasimar working though, I was expecting to
select 'Aasimar' as a race, and then have a racial subrace option on the
other tab, but that's not working. There must be a setting on one of them
that is wrong, can you check on that please?

Cheers
Dave

**Comment by FerretDave** [comment]
Greetings,

My next project needs to be to sit down and work through how to use GIT
properly !

from a clean directory, I run 'git -> clone', from the right click context
menu, and it runs:
git.exe clone --origin master --progress -v "
https://github.com/BahamutDragon/pcgen.git" "F:\Data\GitHub\pcgen"

and it seems determined to always bring down the 6.4.1 branch, rather than
master...

So, will be spending some time learning GIT and not doing any updates for a
while, especially as I now no longer have a working copy of the datasets to
work with...

Cheers
Dave

**Comment by BahamutDragon** [comment]
Mate,

Git Clone is working fine. It defaults to the branch listed as default.

To gain access to the other branches you need to use the git fetch command. Then checkout the myreponame/master

**Comment by BahamutDragon** [comment]
due to version updates, master is now default.

**Comment by FerretDave** [comment]
WooHoo! That's fixed it, thanks ;-)

**Comment by FerretDave** [comment]
Greetings,

I'll keep my personalised/modified DESC's in homebrew, but how do you feel
about my short DESC on scrolls ? Added to your source or kept in my
homebrew?

Cheers
Dave

**Comment by FerretDave** [comment]
additional - various spell DESC's are 'as per blah except' - that's a pet
hate of mine, having to cross reference them, so I add the 'blah' desc onto
the current spell and reword (slightly) to account for the 'except' ruling.

How do you feel about that? Added to your source or kept in my homebrew?

**Comment by BahamutDragon** [comment]
short DESC on scrolls ? Yes

various spell DESC's are 'as per blah except' - that's a pet hate of mine, having to cross reference them, so I add the 'blah' desc onto the current spell and reword (slightly) to account for the 'except' ruling. How do you feel about that? Yes, add.

**Comment by FerretDave** [comment]
cool.

**Pull request closed without merging**
