### PR TITLE
Fix error Core Book 3.5 Tome of Magic

### PR DESCRIPTION
**Pull request by Talaren**
EQUIP was wrong replaced with EQUIPMENT.

### CODE REVIEW

**Comment by BahamutDragon** [comment]
Thanks mate!

**Comment by Talaren** [comment]
no problem i work current on book version 3.5 D&D WoW Core Rule 2nd edition so i see the error in the console ;)

**Comment by BahamutDragon** [comment]
Fantastic!

Good to see an old set getting a breath of new life.

**Comment by Talaren** [comment]
currently i fight with the tags, do you have a list with all possible tags in the sections? i try to make the domains from the healer, but the domain system is complex ( healer are Druid + Priest + Shaman ) on level 1 you became the first domain (lesser) on level 10 the first domain (greater) and the second domain (lesser) on level 20 the second domain (greater) on domain (lesser/greater) is the spell list and on the special e.g. Healing (Lesser) is Greater Healing or Healing(Greater) is Protection Aura and you have Faiths ( of Azeroth ) e.g. The Ancients of the Night Elves has Domains: Animal, Healing, War or The Faith of the Holy Light has Healing, Protection, War or The Cult of the Burning Legion has Death, Destruction, War. A Priest must choice a Faith of Azeroth the druid or shaman easier. druid are Animal or Wild, shaman are Elements or Spirits. Do you have an idee for this situation? will be hapy for every tip.

**Comment by BahamutDragon** [comment]
Hi mate,

Best to take this discussion to a proper channel. WoW does not relate to a pull request fixing Tome of Magic. 

Either open a new issue (https://github.com/BahamutDragon/pcgen/issues/new), email me direct (bahamutdragon2013@gmail.com), or join our yahoo home-brew discussion group  (http://games.groups.yahoo.com/group/bd_games/).

I will work on drafting a proper reply to your questions and respond by the channel you choose to use.

Best,

**Pull request merged**
